language: go

go:
  - 1.12.x

go_import_path: mdata_go/src

dist: xenial

# Phase 1: Grab dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y  -q --allow-downgrades pkg-config build-essential python3-grpcio-tools=1.1.3-1 openssl libzmq3-dev libssl-dev

install: ./ci-scripts/install-dependencies.sh

# Phase 2: Testing
script:
  - go test -v ./...

# Phase 3: Build Binaries


# Phase 4: Deploy Binaries