language: go
go:
- 1.12.x
git:
  depth: 1
dist: xenial
before_install:
- sudo apt-get update
- sudo apt-get install -y  -q --allow-downgrades pkg-config build-essential openssl
  libzmq3-dev libssl-dev
install: "./ci-scripts/install-dependencies.sh"
script:
- go test -v ./...
- go build -v -x -o mdata -ldflags "-X main.Rev=`git rev-parse --short HEAD`" ./src/mdata_client
- go build -v -x -o sawtooth-mdata-tp-go -ldflags "-X main.Rev=`git rev-parse --short HEAD`" ./src/mdata_processor
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: iLjHZPv4JDetBq1waNZ68luoEtH9upsO9Vc1EX77Ej/nanSDRZopFRL1xIfu9a2ZeGA8qRv56M/JftST3mB0Gvox3onA8dvhcPFeDyypfCc3T8HMo5n8mxbE3gT3Mcp8U6JiRqOrCsnQoewfwBZgXBjVAwlZYWrKUNJnflGnbzL+8/ckxWN4eFj+nv5+RBYONDYuypG8PWkz0sAY50EIf3gLZXuuDvgDYs+5Ewx7qegZPuqWDBvYiqf/Er1kmH0DQdOiJ9k/f0SvwaNu8Im5MqcF/PBGKwdscemVIgIWrf2WmY9JULhFdj3aKecixGkOnQDmbGA1riMgfxEgK6nmn9nfffG1pkBA1k/ntuVP6bB1r3akDDKy92JCyZA7OMesLHsjcXN43Rcz/cevuFqlld6L35rXrIjANM4rQWRv00o9iFhZvXayjYEyQq5PRAr+9AE2iC0tMGswyc9nmoYr9hQ4wwNoWbGCK0A7KvG5GIC28lOZgbohuX0LeIkgWsHGvG7rSPR/0qAMJ1W/Ke5xgwpzRzZG/BBj1S9FoEV3tJ7oND60vntdfuDDZcisHXYTY/z9XdiiVbdiRzb+fNB+oqj8EAcd0I2/FkfiL29Ar/oCeI+xKcbXk9JilDr6mCqk0RScpwNRLhR4h/Fu5jS0d+FcCZQFCHRukDNG+RLe4x0=
  file:
  - mdata
  - sawtooth-mdata-tp-go
  on:
    repo: tross-tyson/mdata_go
    tags: true