language: go
go:
- 1.12.x
git:
  depth: 1
dist: xenial
before_install:
- sudo apt-get update
- sudo apt-get install -y  -q --allow-downgrades pkg-config build-essential openssllibzmq3-dev libssl-dev
install: "./ci-scripts/install-dependencies.sh"
script:
- go test -v ./...
- go build -v -x -o mdata -ldflags "-X main.Rev=`git rev-parse --short HEAD`" ./src/mdata_client
- go build -v -x -o sawtooth-mdata-tp-go -ldflags "-X main.Rev=`git rev-parse --short HEAD`" ./src/mdata_processor
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eH+M3yBYIjv9EsME0W3UIElqj16Ld4+KWhLfmbQxeo2LNTguE9ocBJG+8mxuCl0LEqEkushkHABDh2yU22fGhg4LCLjFWb/8HPxrLuuENU1WeeTsI/K4MyQMYUDrKmZ91RTG7t3eSZjSkjkfvkxLLXv7Z7p5PvtHIjDutlN7lORRdequF0F2m7AsbHhw8W1pJhq6ljrgrSgac219IMRBy2aRCmjkjpQ2H8RITkD8X51gn2j9wNWMsBRfk3i3eycvJSzNFZepjlBtmVkIS531Mz5SK1jASpFc+dkMLziRizet439T5r14MGh8wSX7XMCxieoBOQnpJIMTjyCZojGky/DI4OR2YHot1lkOu0UhvJWQoXVBom+eDdEr3pzQWM37ou1AsBFY8aAW0d/lCH335nZBCiH/L7d3SYTpUFwfAn41sg5q5m0SxHO9TmW7JTu2upU2ED5KisboscDy2/tL7khBqrjJ61V/plS4fqKSqq/9PVBkEo/xs3JTpPKEMVLqXRQhfBOgGFjg/0YSwsjL84zuC2itMIHW85qLGC9YlEgc/koOVWXKV1IvV41eW29Pb9+Xx6yVzPIQBBE/mIfSY87End1DujEpevNTF2Ly/XvzI6SMHNoOoYzpWH22cGxzxeaIJeG4NsFxpidEiBjBi3kJO3JBv0NDf3X2Z2n4HQo=
  file:
  - mdata
  - sawtooth-mdata-tp-go
  on:
    repo: tross-tyson/mdata_go
    tags: true